#ifndef _ALFY_DEFS_H_
#define _ALFY_DEFS_H_

#include "alfy_conf.h"

#define CONFIGSETTINGS_MAGIC 0xDEADBEEF

enum
{
    MENUITEM_NONE = 0,
    // if a unique identifier is needed for a menu item, add it here
    MENUITEM_INTERVAL,
    MENUITEM_ASTRO,
};

enum
{
  TXTFMT_NONE     =      0,
  TXTFMT_BOOL     = 0x0001,
  TXTFMT_TIME     = 0x0002,
  TXTFMT_BULB     = 0x0004,
  TXTFMT_TIMEMS   = 0x0008,
  TXTFMT_TIMELONG = 0x0010,
  TXTFMT_SHUTTER  = 0x0020,
  TXTFMT_ISO      = 0x0040,
  TXTFMT_LCDBRITE = 0x0080,
  TXTFMT_BYTENS   = 0x0100,
  TXTFMT_PROTOCOL = 0x0200,
  TXTFMT_AUTOCFG  = 0xFFFF,
};

enum
{
  BATTSTAT_NONE,
  BATTSTAT_LOW,
  BATTSTAT_CHARGING,
  BATTSTAT_CHARGING_LOW,
  BATTSTAT_FULL,
};

enum
{
  SPRITESHOLDER_FOCUSPULL = 0x01,
  SPRITESHOLDER_INTERVAL  = 0x02,
};

enum
{
    AUTOCONNRES_NONE,
    AUTOCONNRES_QUIT,
    AUTOCONNRES_FOUND_EXISTING,
    AUTOCONNRES_FOUND_EXISTING_NEED_PASSWORD,
    AUTOCONNRES_FOUND_NEW,
};

enum
{
    WIFIPROMPTRET_CANCEL,
    WIFIPROMPTRET_DONE,
    WIFIPROMPTRET_EMPTY,
};

enum
{
    AUTOCONNSTS_NONE,
    AUTOCONNSTS_CONNECTED,
    AUTOCONNSTS_FAILED,
};

enum
{
    WAITGFX_NONE,
    WAITGFX_CONNECTING,
    WAITGFX_UNSUPPORTED,
};

enum
{
    ALLOWEDPROTOCOL_ALL   = 0,
    ALLOWEDPROTOCOL_PTP   = 1,
    ALLOWEDPROTOCOL_HTTP  = 2,
};

#endif
