#ifndef _ALFY_DEFS_H_
#define _ALFY_DEFS_H_

#include "alfy_conf.h"

#define CONFIGSETTINGS_MAGIC 0xDEADBEEF

enum
{
  MENUITEM_END_OF_TABLE = 0,
  MENUITEM_FOCUSSTACK_FAR_1,
  MENUITEM_FOCUSSTACK_FAR_2,
  MENUITEM_FOCUSSTACK_FAR_3,
  MENUITEM_FOCUSSTACK_NEAR_1,
  MENUITEM_FOCUSSTACK_NEAR_2,
  MENUITEM_FOCUSSTACK_NEAR_3,
  MENUITEM_FOCUS_9POINT,
  MENUITEM_REMOTESHUTTER_NOW,
  MENUITEM_REMOTESHUTTER_2S,
  MENUITEM_REMOTESHUTTER_5S,
  MENUITEM_REMOTESHUTTER_10S,
  MENUITEM_RECORDMOVIE,
  MENUITEM_CONFIG,
  MENUITEM_WIFIINFO,
};

enum
{
  ANGLE_IS_FLAT = 0,
  ANGLE_IS_UP,
  ANGLE_IS_DOWN,
};

enum
{
    LEDMODE_NORMAL,
    LEDMODE_BLINK,
    LEDMODE_ON,
};

#endif
