#ifndef _ALFY_CONF_H_
#define _ALFY_CONF_H_

#define SUBMENU_X_OFFSET 5
#define SUBMENU_Y_OFFSET 5

#define PAGINATION_DOT_SIZE      2
#define PAGINATION_SPACE_SIZE    2
#define PAGINATION_BOTTOM_MARGIN 0

#define WELCOME_TIME_MS        10000
#define WELCOME_CONN_TIME_MS   (WELCOME_TIME_MS + 3000)

#define BTN_DEBOUNCE 50

#endif
